// Create web server
// 1. npm i express -S
// 2. npm i body-parser -S
// 3. npm i mongoose -S
// 4. npm i bluebird -S
// 5. npm i nodemon -D
// 6. npm i cors -S
// 7. npm i morgan -S
// 8. npm i express-validator -S
// 9. npm i dotenv -S
// 10. npm i jsonwebtoken -S
// 11. npm i bcrypt -S
// 12. npm i express-graphql -S
// 13. npm i graphql -S
// 14. npm i graphql-tools -S
// 15. npm i graphql-import -S
// 16. npm i apollo-server-express -S
// 17. npm i apollo-link-context -S
// 18. npm i apollo-boost -S
// 19. npm i apollo-link-http -S
// 20. npm i apollo-link-error -S
// 21. npm i apollo-link -S
// 22. npm i apollo-cache-inmemory -S
// 23. npm i graphql-subscriptions -S
// 24. npm i subscriptions-transport-ws -S
// 25. npm i graphql-playground-middleware-express -S
// 26. npm i graphql-tools -S
// 27. npm i graphql-import -S
// 28. npm i graphql-type-json -S
// 29. npm i graphql-type-long -S
// 30. npm i graphql-type-datetime -S
// 31. npm i graphql-iso-date -S
// 32. npm i graphql-iso-date-2 -S
// 33. npm i graphql-iso-date-2 -S
// 34. npm i graphql-date -S
// 35. npm i graphql-iso-date -S
// 36. npm i graphql-iso-date-2 -S
// 37. npm i graphql-iso-date-2 -S
// 38. npm i graphql-date -S
// 39. npm i graphql-iso-date -S
// 40. npm i graphql-iso-date-2 -S
// 41. npm i graphql-iso-date